export const actionType = {
    ALL_PRODUCT_LOADING: "ALL_PRODUCT_LOADING",
    ALL_PRODUCT: "ALL_PRODUCT",
    ALL_PRODUCT_ERROR: "ALL_PRODUCT_ERROR",
    SINGLE_PRODUCT_LOADING: "SINGLE_PRODUCT_LOADING",
    SINGLE_PRODUCT: "SINGLE_PRODUCT",
    SINGLE_PRODUCT_ERROR: "SINGLE_PRODUCT_ERROR",
}